window.__KICKOFF_RUNTIME_CONFIG__ = Object.freeze(
{
  "VITE_SUPABASE_URL": "",
  "VITE_SUPABASE_ANON_KEY": "",
  "VITE_SUPABASE_REDIRECT_URL": "https://olive8882-1996.github.io/kickoff-lock-agent/",
  "VITE_SUPABASE_SHARE_BUCKET": "kickoff-share-cards",
  "VITE_PUBLIC_APP_URL": "https://olive8882-1996.github.io/kickoff-lock-agent/",
  "VITE_DATA_PROXY_URL": "",
  "VITE_DATA_PROXY_SAME_ORIGIN": "0",
  "VITE_APIFOOTBALL_KEY": "",
  "VITE_APIFOOTBALL_ENRICHMENT_LIMIT": "12",
  "VITE_FOOTBALL_DATA_TOKEN": "",
  "VITE_FOOTBALL_DATA_COMPETITION": "WC",
  "VITE_THESPORTSDB_KEY": "123",
  "VITE_THESPORTSDB_LEAGUE_ID": "4429",
  "VITE_THESPORTSDB_SEASON": "2026",
  "VITE_THESPORTSDB_ENRICHMENT_LIMIT": "8",
  "VITE_ODDS_API_KEY": "",
  "VITE_ODDS_API_SPORT_KEY": "",
  "VITE_FILECOIN_SEAL_API": "",
  "VITE_FILECOIN_SEAL_SAME_ORIGIN": "0",
  "VITE_FILECOIN_SEAL_TOKEN": ""
}
);
