window.__KICKOFF_RUNTIME_CONFIG__ = Object.freeze(
{
  "VITE_SUPABASE_URL": "https://zumekowyumajlmkqdsqw.supabase.co",
  "VITE_SUPABASE_ANON_KEY": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1bWVrb3d5dW1hamxta3Fkc3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM0OTAxNTQsImV4cCI6MjA5OTA2NjE1NH0.rwPA5kMNAfREOw-kMIr0fK7ArjW3GV4JNmWJ4V5yYcE",
  "VITE_SUPABASE_REDIRECT_URL": "https://olive8882-1996.github.io/kickoff-lock-agent/",
  "VITE_SUPABASE_SHARE_BUCKET": "kickoff-share-cards",
  "VITE_PUBLIC_APP_URL": "https://olive8882-1996.github.io/kickoff-lock-agent/",
  "VITE_DATA_PROXY_URL": "",
  "VITE_DATA_PROXY_SAME_ORIGIN": "0",
  "VITE_APIFOOTBALL_KEY": "72f3c44c58b6947c080803ba32ad6c1e",
  "VITE_APIFOOTBALL_ENRICHMENT_LIMIT": "12",
  "VITE_FOOTBALL_DATA_TOKEN": "",
  "VITE_FOOTBALL_DATA_COMPETITION": "WC",
  "VITE_THESPORTSDB_KEY": "123",
  "VITE_THESPORTSDB_LEAGUE_ID": "4429",
  "VITE_THESPORTSDB_SEASON": "2026",
  "VITE_THESPORTSDB_ENRICHMENT_LIMIT": "8",
  "VITE_ODDS_API_KEY": "8282816b1270c40a2fe50d93970fb209",
  "VITE_ODDS_API_SPORT_KEY": "soccer_fifa_world_cup",
  "VITE_FILECOIN_SEAL_API": "",
  "VITE_FILECOIN_SEAL_SAME_ORIGIN": "0",
  "VITE_FILECOIN_SEAL_TOKEN": ""
}
);
